{{- if .Values.networkPolicy.create }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: sda-orch
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "sda.fullname" . }}
  policyTypes:
  - Egress
  egress:
  - to:
    {{- if .Values.networkPolicy.brokerNamespace }}
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.brokerNamespace }}
    {{- end }}
    - podSelector:
        matchLabels:
          role: broker
    ports:
    - protocol: TCP
      port: 5671
---
{{- end }}