{{- if .Values.networkPolicy.create }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: sda-mq
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "sda.fullname" . }}
  policyTypes:
  - Ingress
  ingress:
    - ports:
      - port: postgres
      - protocol: TCP
        port: 5671
    - from:
      - podSelector:
          matchLabels:
{{ .Values.networkPolicy.matchLabels | trim | indent 12 }}
---
{{- end }}