apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: Y29uc29sZQ== # console
  CONSOLE_SECRET_KEY: Y29uc29sZTEyMw== # console123
kind: Secret
metadata:
  name: sda-s3-user-secret
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: sda-s3-configuration
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
